"""v1

Revision ID: 08159feaaaef
Revises: 
Create Date: 2026-07-05 11:39:43.834265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08159feaaaef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('team_members', sa.Column('donation_status', sa.String(length=30), nullable=False))
    op.add_column('team_members', sa.Column('donation_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('team_members', sa.Column('donation_confirmed_by', sa.UUID(), nullable=True))
    op.add_column('team_members', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('team_members', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('team_members', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('team_members', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('team_members', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('team_members', sa.Column('active', sa.Boolean(), nullable=False))
    op.alter_column('team_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('team_members_member_matricula_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['donation_confirmed_by'], ['id'])
    op.drop_column('team_members', 'member_matricula')
    op.drop_column('team_members', 'status')
    op.drop_column('team_members', 'member_cpf')
    op.drop_column('team_members', 'member_name')
    op.add_column('teams', sa.Column('season_id', sa.UUID(), nullable=False))
    op.add_column('teams', sa.Column('modality_id', sa.UUID(), nullable=False))
    op.add_column('teams', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('teams', sa.Column('captain_id', sa.UUID(), nullable=True))
    op.add_column('teams', sa.Column('invite_token', sa.UUID(), nullable=False))
    op.add_column('teams', sa.Column('token_active', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('teams', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('rejected_by', sa.UUID(), nullable=True))
    op.add_column('teams', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('teams', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='teamstatus'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('teams', 'photo',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'teams', ['invite_token'])
    op.create_foreign_key(None, 'teams', 'seasons', ['season_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'users', ['captain_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'modalities', ['modality_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'teams', 'users', ['approved_by'], ['id'])
    op.drop_column('teams', 'modality')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'role')
    op.add_column('teams', sa.Column('modality', postgresql.ENUM('FUTSAL', 'BASQUETE', 'VOLEI', 'VOLEI_DE_AREIA', 'HANDEBOL', 'QUEIMADA', name='modalitytype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='unique')
    op.alter_column('teams', 'photo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('teams', 'status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='teamstatus'),
               existing_nullable=False)
    op.alter_column('teams', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('teams', 'deleted_at')
    op.drop_column('teams', 'rejected_by')
    op.drop_column('teams', 'rejected_at')
    op.drop_column('teams', 'approved_by')
    op.drop_column('teams', 'approved_at')
    op.drop_column('teams', 'submitted_at')
    op.drop_column('teams', 'token_active')
    op.drop_column('teams', 'invite_token')
    op.drop_column('teams', 'captain_id')
    op.drop_column('teams', 'owner_id')
    op.drop_column('teams', 'modality_id')
    op.drop_column('teams', 'season_id')
    op.add_column('team_members', sa.Column('member_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('member_cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('status', postgresql.ENUM('PENDING_DONATION', 'DONATION_CONFIRMED', name='teammemberstatus'), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('member_matricula', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_member_matricula_fkey'), 'team_members', 'users', ['member_matricula'], ['matricula'])
    op.alter_column('team_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('team_members', 'active')
    op.drop_column('team_members', 'deleted_at')
    op.drop_column('team_members', 'modified_at')
    op.drop_column('team_members', 'created_at')
    op.drop_column('team_members', 'id')
    op.drop_column('team_members', 'joined_at')
    op.drop_column('team_members', 'donation_confirmed_by')
    op.drop_column('team_members', 'donation_confirmed_at')
    op.drop_column('team_members', 'donation_status')
    op.drop_column('team_members', 'role')
    # ### end Alembic commands ###
