"""v3

Revision ID: 6906e02e3cee
Revises: 7b80a5f923ca
Create Date: 2026-07-17 15:48:00.067600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6906e02e3cee'
down_revision: Union[str, Sequence[str], None] = '7b80a5f923ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('monitor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'matches', 'users', ['monitor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'monitor_id')
    # ### end Alembic commands ###
