"""v5

Revision ID: b5886801e33d
Revises: f61e65246346
Create Date: 2026-07-18 13:28:49.389720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5886801e33d'
down_revision: Union[str, Sequence[str], None] = 'f61e65246346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modality_configurations', sa.Column('modality_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('modality_configurations_season_modality_id_key'), 'modality_configurations', type_='unique')
    op.create_unique_constraint(None, 'modality_configurations', ['modality_id'])
    op.drop_constraint(op.f('modality_configurations_season_modality_id_fkey'), 'modality_configurations', type_='foreignkey')
    op.create_foreign_key(None, 'modality_configurations', 'modalities', ['modality_id'], ['id'])
    op.drop_column('modality_configurations', 'season_modality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modality_configurations', sa.Column('season_modality_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modality_configurations', type_='foreignkey')
    op.create_foreign_key(op.f('modality_configurations_season_modality_id_fkey'), 'modality_configurations', 'season_modalities', ['season_modality_id'], ['id'])
    op.drop_constraint(None, 'modality_configurations', type_='unique')
    op.create_unique_constraint(op.f('modality_configurations_season_modality_id_key'), 'modality_configurations', ['season_modality_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('modality_configurations', 'modality_id')
    # ### end Alembic commands ###
