"""v6

Revision ID: c004b9fe7984
Revises: b5886801e33d
Create Date: 2026-07-24 09:21:01.346034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c004b9fe7984'
down_revision: Union[str, Sequence[str], None] = 'b5886801e33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volleyball_modality_configurations',
    sa.Column('modality_configuration_id', sa.UUID(), nullable=False),
    sa.Column('points_per_set', sa.Integer(), nullable=False),
    sa.Column('final_set_points', sa.Integer(), nullable=False),
    sa.Column('sets_to_win', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modality_configuration_id'], ['modality_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modality_configuration_id')
    )
    op.create_table('match_sets',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('team1_points', sa.Integer(), nullable=False),
    sa.Column('team2_points', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'set_number', name='uq_match_sets_match_id_set_number')
    )
    op.add_column('matches', sa.Column('team1_sets_won', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team2_sets_won', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'team2_sets_won')
    op.drop_column('matches', 'team1_sets_won')
    op.drop_table('match_sets')
    op.drop_table('volleyball_modality_configurations')
    # ### end Alembic commands ###
