"""v7

Revision ID: e89b398e0d96
Revises: c004b9fe7984
Create Date: 2026-07-24 20:35:13.454439

"""
from typing import Sequence, Union

from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = 'e89b398e0d96'
down_revision: Union[str, Sequence[str], None] = 'c004b9fe7984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_prevent_match_sets_mutation = PGFunction(
        schema="public",
        signature="prevent_match_sets_mutation()",
        definition="RETURNS trigger AS $$\n    BEGIN\n        IF TG_OP = 'TRUNCATE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: TRUNCATE is not allowed'\n                USING ERRCODE = '23000';\n        END IF;\n\n        IF TG_OP = 'DELETE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: DELETE is not allowed (id=%)',\n                OLD.id\n                USING ERRCODE = '23000';\n        END IF;\n\n        IF TG_OP = 'UPDATE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: UPDATE is not allowed (id=%)',\n                OLD.id\n                USING ERRCODE = '23000';\n        END IF;\n\n        RETURN NULL;\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.create_entity(public_prevent_match_sets_mutation)

    public_match_sets_trg_match_sets_immutable = PGTrigger(
        schema="public",
        signature="trg_match_sets_immutable",
        on_entity="public.match_sets",
        is_constraint=False,
        definition='BEFORE UPDATE OR DELETE ON public.match_sets\n    FOR EACH ROW\n    EXECUTE FUNCTION prevent_match_sets_mutation()'
    )
    op.create_entity(public_match_sets_trg_match_sets_immutable)

    public_match_sets_trg_match_sets_immutable_truncate = PGTrigger(
        schema="public",
        signature="trg_match_sets_immutable_truncate",
        on_entity="public.match_sets",
        is_constraint=False,
        definition='BEFORE TRUNCATE ON public.match_sets\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION prevent_match_sets_mutation()'
    )
    op.create_entity(public_match_sets_trg_match_sets_immutable_truncate)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_match_sets_trg_match_sets_immutable_truncate = PGTrigger(
        schema="public",
        signature="trg_match_sets_immutable_truncate",
        on_entity="public.match_sets",
        is_constraint=False,
        definition='BEFORE TRUNCATE ON public.match_sets\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION prevent_match_sets_mutation()'
    )
    op.drop_entity(public_match_sets_trg_match_sets_immutable_truncate)

    public_match_sets_trg_match_sets_immutable = PGTrigger(
        schema="public",
        signature="trg_match_sets_immutable",
        on_entity="public.match_sets",
        is_constraint=False,
        definition='BEFORE UPDATE OR DELETE ON public.match_sets\n    FOR EACH ROW\n    EXECUTE FUNCTION prevent_match_sets_mutation()'
    )
    op.drop_entity(public_match_sets_trg_match_sets_immutable)

    public_prevent_match_sets_mutation = PGFunction(
        schema="public",
        signature="prevent_match_sets_mutation()",
        definition="RETURNS trigger AS $$\n    BEGIN\n        IF TG_OP = 'TRUNCATE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: TRUNCATE is not allowed'\n                USING ERRCODE = '23000';\n        END IF;\n\n        IF TG_OP = 'DELETE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: DELETE is not allowed (id=%)',\n                OLD.id\n                USING ERRCODE = '23000';\n        END IF;\n\n        IF TG_OP = 'UPDATE' THEN\n            RAISE EXCEPTION\n                'match_sets is immutable\\: UPDATE is not allowed (id=%)',\n                OLD.id\n                USING ERRCODE = '23000';\n        END IF;\n\n        RETURN NULL;\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_prevent_match_sets_mutation)

    # ### end Alembic commands ###
