from enum import Enum


class AuditAction(Enum):
    SEASON_CREATED = "SEASON_CREATED"
    SEASON_DATES_UPDATED = "SEASON_DATES_UPDATED"
    SEASON_REGISTRATION_CLOSED = "SEASON_REGISTRATION_CLOSED"
    SEASON_REGISTRATION_REOPENED = "SEASON_REGISTRATION_REOPENED"
    SEASON_FINISHED = "SEASON_FINISHED"
    MODALITY_CREATED = "MODALITY_CREATED"
    TEAM_SUBMITTED = "TEAM_SUBMITTED"
    TEAM_MEMBER_JOINED = "TEAM_MEMBER_JOINED"
    TEAM_MEMBER_LEFT = "TEAM_MEMBER_LEFT"
    TEAM_MEMBER_REMOVED = "TEAM_MEMBER_REMOVED"
    TEAM_CAPTAIN_SELECTED = "TEAM_CAPTAIN_SELECTED"
    BRACKET_CREATED = "BRACKET_CREATED"
    BRACKET_RESORTED = "BRACKET_RESORTED"
    MATCH_UPDATED = "MATCH_UPDATED"
    MATCH_DELETED = "MATCH_DELETED"
    MATCH_STARTED = "MATCH_STARTED"