from enum import Enum


class EventType(Enum):
    MATCH_STARTED = "MATCH_STARTED"
    MATCH_END = "MATCH_END"
    PERIOD_START = "PERIOD_START"
    PERIOD_END = "PERIOD_END"
    GOAL = "GOAL"
    POINT = "POINT"
    CARD_YELLOW = "CARD_YELLOW"
    CARD_RED = "CARD_RED"
    EXPULSION = "EXPULSION"
    SET_END = "SET_END"
    PENALTY_GOAL = "PENALTY_GOAL"
    PENALTY_MISS = "PENALTY_MISS"